POST /
Content-Type: application/json
Host: localhost:3005

[
  {
    "description": "Faltam 10 dias para vencimento do plano gratuito BANCO DE DADOS",
    "id": "63c940eac539d0378f5df59d",
    "isError": false,
    "resource": "Enneagram-API",
    "serviceToDispare": "discord",
    "title": "Vencimento do Plano Gratuito"
  },
  {
    "description": "Falha ao Processar Lote de Images, pois as mesmas não estão no formato adequado",
    "id": "63c940eac539d0378f5df59d",
    "isError": true,
    "resource": "Enneagram-API",
    "serviceToDispare": "discord",
    "title": "Falha ao Processar Lote de Imagens "
  },
  {
    "description": "Faltam 10 dias para vencimento do plano gratuito BANCO DE DADOS",
    "id": "63c940eac539d0378f5df59d",
    "isError": false,
    "resource": "Enneagram-API",
    "serviceToDispare": "discord",
    "title": "Vencimento do Plano Gratuito"
  }, {
    "description": "Falha ao Processar Lote de Images",
    "id": "63c940eac539d0378f5df59d",
    "isError": true,
    "resource": "Enneagram-API",
    "serviceToDispare": "discord",
    "title": "Limite de retry Atingido"
  }
]
